# Generated by Django 5.2.8 on 2025-11-24 14:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('engine_type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('total_objects', models.IntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('processing_time', models.FloatField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单总额')),
                ('products', models.JSONField(verbose_name='商品列表详情')),
                ('status', models.CharField(default='success', max_length=20, verbose_name='状态')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='水果名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='销售单价')),
                ('stock', models.FloatField(default=0, verbose_name='库存数量(斤)')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='进货单价')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='条形码')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('bbox_x1', models.IntegerField(default=0)),
                ('bbox_y1', models.IntegerField(default=0)),
                ('bbox_x2', models.IntegerField(default=0)),
                ('bbox_y2', models.IntegerField(default=0)),
                ('class_id', models.IntegerField(default=0)),
                ('detection_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.detectionhistory')),
            ],
        ),
    ]
